[project]
name = "pds-exports"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "astropy>=6.1.7",
    "lxml>=6.0.1",
    "numpy>=2.2.6",
]
